### ISSUE TITLE
Error importing kasper

### ISSUE THREAD

**Issue by raspberrypieman** [janickr/kaspersmicrobit#1]
Hi,
  I installed kaspersmicrobit using pip on my python 3.9.1 system running on Windows/10 and got no errors, see below:

> C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>pip install kaspersmicrobit
> Collecting kaspersmicrobit
>   Downloading kaspersmicrobit-0.3.3-py3-none-any.whl (44 kB)
>      ---------------------------------------- 44.6/44.6 kB 2.3 MB/s eta 0:00:00
> Collecting bleak
>   Downloading bleak-0.15.1-py2.py3-none-any.whl (123 kB)
>      ---------------------------------------- 124.0/124.0 kB 7.1 MB/s eta 0:00:00
> Collecting typing-extensions>=4.2.0
>   Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
> Collecting bleak-winrt>=1.1.1
>   Downloading bleak_winrt-1.1.1-cp39-cp39-win_amd64.whl (345 kB)
>      ---------------------------------------- 345.7/345.7 kB 10.5 MB/s eta 0:00:00
> Installing collected packages: bleak-winrt, typing-extensions, bleak, kaspersmicrobit
>   WARNING: The script bleak-lescan.exe is installed in 'c:\users\raspberry\appdata\local\programs\python\python39\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed bleak-0.15.1 bleak-winrt-1.1.1 kaspersmicrobit-0.3.3 typing-extensions-4.3.0

After this I started python 3.9.1 and executed this one line:
from kaspersmicrobit import KaspersMicrobit

but got the following errors:

> Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from kaspersmicrobit import KaspersMicrobit
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\__init__.py", line 5, in <module>
>     from .kaspersmicrobit import KaspersMicrobit  # noqa: F401
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\kaspersmicrobit.py", line 14, in <module>
>     from .services.io_pin import IOPinService
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\services\io_pin.py", line 181, in <module>
>     class IOPinService:
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\services\io_pin.py", line 198, in IOPinService
>     def notify_data(self, callback: Callable[[[PinValue]], None]):
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py", line 869, in __getitem__
>     return self.__getitem_inner__(params)
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py", line 262, in inner
>     return func(*args, **kwds)
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py", line 879, in __getitem_inner__
>     args = tuple(_type_check(arg, msg) for arg in args)
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py", line 879, in <genexpr>
>     args = tuple(_type_check(arg, msg) for arg in args)
>   File "C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py", line 151, in _type_check
>     raise TypeError(f"{msg} Got {arg!r:.100}.")
> TypeError: Callable[[arg, ...], result]: each arg must be a type. Got [<class 'kaspersmicrobit.services.io_pin.PinValue'>].
> >>>

Am I doing something wrong?

**Comment by janickr** [comment]
Hi @raspberrypieman 

Thanks for reporting this, I'm able to reproduce the issue. 

I think this is caused by an issue in Python 3.9.1 ( https://github.com/python/cpython/issues/86361 ) which was fixed in python 3.9.2. 

Can you upgrade your python version to the latest 3.9 release (or the latest 3.10 release)?

**Comment by janickr** [comment]
I may have found a way to fix it for 3.9.1 as well, I'll take a look later today.

**Comment by raspberrypieman** [comment]
Hi Janick,
    I tried to update using:

$  pip install --upgrade kaspersmicrobit

but I still got same error in Python 3.9.1 so I uninstalled kaspersmicrobit
and reinstalled it as below, but still get the same error.

C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>pip
uninstall kaspersmicrobit
Found existing installation: kaspersmicrobit 0.3.3
Uninstalling kaspersmicrobit-0.3.3:
  Would remove:

c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages\kaspersmicrobit-0.3.3.dist-info\*

c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages\kaspersmicrobit\*
Proceed (Y/n)? y
  Successfully uninstalled kaspersmicrobit-0.3.3

C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>pip
install kaspersmicrobit
Collecting kaspersmicrobit
  Using cached kaspersmicrobit-0.3.3-py3-none-any.whl (44 kB)
Requirement already satisfied: bleak in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from kaspersmicrobit) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from bleak->kaspersmicrobit) (4.3.0)
Requirement already satisfied: bleak-winrt>=1.1.1 in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from bleak->kaspersmicrobit) (1.1.1)
Installing collected packages: kaspersmicrobit
Successfully installed kaspersmicrobit-0.3.3

Then retried in my Python 3.9.1 as you suggested but go a similar error:

Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from kaspersmicrobit import KaspersMicrobit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\__init__.py",
line 5, in <module>
    from .kaspersmicrobit import KaspersMicrobit  # noqa: F401
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\kaspersmicrobit.py",
line 14, in <module>
    from .services.io_pin import IOPinService
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\services\io_pin.py",
line 181, in <module>
    class IOPinService:
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\services\io_pin.py",
line 198, in IOPinService
    def notify_data(self, callback: Callable[[[PinValue]], None]):
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 869, in __getitem__
    return self.__getitem_inner__(params)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 262, in inner
    return func(*args, **kwds)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 879, in __getitem_inner__
    args = tuple(_type_check(arg, msg) for arg in args)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 879, in <genexpr>
    args = tuple(_type_check(arg, msg) for arg in args)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 151, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[[arg, ...], result]: each arg must be a type. Got
[<class 'kaspersmicrobit.services.io_pin.PinValue'>].
>>>

**Comment by janickr** [comment]
Hi @raspberrypieman 

It is fixed on master, but I have to publish the release first :)

Just a few more minutes

**Comment by janickr** [comment]
I uploaded the release to Pypi, can you try now?

$  pip install --upgrade kaspersmicrobit

Thanks!

**Comment by raspberrypieman** [comment]
Sorry, I hope I am not doing something silly - I tried again:

C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>pip
install --upgrade kaspersmicrobit
Requirement already satisfied: kaspersmicrobit in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(0.3.3)
Requirement already satisfied: bleak in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from kaspersmicrobit) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from bleak->kaspersmicrobit) (4.3.0)
Requirement already satisfied: bleak-winrt>=1.1.1 in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from bleak->kaspersmicrobit) (1.1.1)

C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>..\python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from kaspersmicrobit import KaspersMicrobit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\__init__.py",
line 5, in <module>
    from .kaspersmicrobit import KaspersMicrobit  # noqa: F401
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\kaspersmicrobit.py",
line 14, in <module>
    from .services.io_pin import IOPinService
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\services\io_pin.py",
line 181, in <module>
    class IOPinService:
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\site-packages\kaspersmicrobit\services\io_pin.py",
line 198, in IOPinService
    def notify_data(self, callback: Callable[[[PinValue]], None]):
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 869, in __getitem__
    return self.__getitem_inner__(params)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 262, in inner
    return func(*args, **kwds)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 879, in __getitem_inner__
    args = tuple(_type_check(arg, msg) for arg in args)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 879, in <genexpr>
    args = tuple(_type_check(arg, msg) for arg in args)
  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\lib\typing.py",
line 151, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[[arg, ...], result]: each arg must be a type. Got
[<class 'kaspersmicrobit.services.io_pin.PinValue'>].

**Comment by raspberrypieman** [comment]
Janick,
    Well Done - I think you have solved it - Thanks very much

C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>pip
install --upgrade kaspersmicrobit
Requirement already satisfied: kaspersmicrobit in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(0.3.3)
Collecting kaspersmicrobit
  Downloading kaspersmicrobit-0.3.4-py3-none-any.whl (44 kB)
     ---------------------------------------- 44.7/44.7 kB 2.2 MB/s eta
0:00:00
Requirement already satisfied: bleak in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from kaspersmicrobit) (0.15.1)
Requirement already satisfied: bleak-winrt>=1.1.1 in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from bleak->kaspersmicrobit) (1.1.1)
Requirement already satisfied: typing-extensions>=4.2.0 in
c:\users\raspberry\appdata\local\programs\python\python39\lib\site-packages
(from bleak->kaspersmicrobit) (4.3.0)
Installing collected packages: kaspersmicrobit
  Attempting uninstall: kaspersmicrobit
    Found existing installation: kaspersmicrobit 0.3.3
    Uninstalling kaspersmicrobit-0.3.3:
      Successfully uninstalled kaspersmicrobit-0.3.3
Successfully installed kaspersmicrobit-0.3.4

C:\Users\Raspberry\AppData\Local\Programs\Python\Python39\Scripts>..\python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from kaspersmicrobit import KaspersMicrobit
>>>

**Comment by raspberrypieman** [comment]
Janick,
       You solved the issue I had with installing Kaspersmicrobit - thanks.
Now I move on to trying your initial test program but I cannot seem to
connect to any of my microbits.

I have now installed Python 3.10.7 and pip installed kaspersmicrobit

I am running this code:

*import time*
*from kaspersmicrobit import KaspersMicrobit*
*CHANGE_THIS_TO_YOUR_MICROBIT_BLUETOOTH_ADDRESS = 'D6:66:C1:A7:CF:0F'*
*def pressed(button):*
*    print(f"button {button} pressed")  *
*with KaspersMicrobit(CHANGE_THIS_TO_YOUR_MICROBIT_BLUETOOTH_ADDRESS) as
microbit:*
*    microbit.buttons.on_button_a(press=pressed)*
*    time.sleep(10)*


and getting this error:

*Traceback (most recent call last):*
*  File
"Y:\Source\Python\_Python3\_MyTools\Microbits\kaspers_microbit_test.py",
line 14, in <module>*
*    with KaspersMicrobit(CHANGE_THIS_TO_YOUR_MICROBIT_BLUETOOTH_ADDRESS)
as microbit:*
*  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python310\lib\site-packages\kaspersmicrobit\kaspersmicrobit.py",
line 103, in __enter__*
*    self.connect()*
*  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python310\lib\site-packages\kaspersmicrobit\kaspersmicrobit.py",
line 120, in connect*
*    self._device.connect()*
*  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python310\lib\site-packages\kaspersmicrobit\bluetoothdevice.py",
line 68, in connect*
*    self.loop.run_async(self.client.connect()).result()*
*  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py",
line 458, in result*
*    return self.__get_result()*
*  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py",
line 403, in __get_result*
*    raise self._exception*
*  File
"C:\Users\Raspberry\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py",
line 213, in connect*
*    raise BleakError(*
*bleak.exc.BleakError: Device with address D6:66:C1:A7:CF:0F was not found.*


I attach a screen-shot of the hardware address as shown by WIndows Settings.
Bluetooth is on and the microbit is paired but not connected (as
recommended)

What else can I do to try to diagnose this problem - I have tried with 3
different microbits ?

Regards,
Martyn

**Comment by janickr** [comment]
Hi Martyn,

Can you open a new issue for this? 
Thanks!

Janick
